workflow:
  - .github/**/*
  - ./.gitignore
  - ./.npmignore

config:
  - .sharedconfig.yml
  - .husky/**/*

project:
  - package-lock.json
  - package.json
  - LICENSE

docs:
  - any: ['docs/**/*', '*.md', '.ghinfo']

shared-config:workflow:
  - .config/.github/**/*
  - .config/.gitignore
  - .config/.npmignore

shared-config:code-style:
  - .config/.editorconfig
  - .config/.eslintignore
  - .config/.eslintrc
  - .config/.prettierignore
  - .config/.prettierrc

shared-config:test:
  - .config/jest.config.js

shared-config:ts:
  - .config/tsconfig.json

shared-config:scripts:
  - scripts.js

shared-config:dependencies:
  - dependencies.js
