sharedDir: '.config'
outputDir: 'lib'

mergeRules:
  '.vscode/cspell.json': ['words', 'ignorePaths']
  '.vscode/launch.json': ['configurations']
  '.vscode/settings.json':
    [
      'javascript.preferences.importModuleSpecifierEnding',
      'typescript.preferences.importModuleSpecifierEnding',
      'typescript.preferences.importModuleSpecifier',
      'material-icon-theme.files.associations',
    ]
  '.gitignore': true
  '.npmignore': true
  '.prettierignore': true

ignorePatterns:
  '.gitignore': ['/.editorconfig', '/.prettierignore', '/.prettierrc', '/.vscode/']
  '.npmignore': ['.editorconfig', '.prettierignore', '.prettierrc', '.vscode']

scripts:
  'prepare': 'run-s prepare:*'
  'prepare:vscode': 'vscode-shared-config'
  'lint': 'run-s lint:*'
  'lint:spell': 'cspell -c .vscode/cspell.json --no-summary "**/*.{js,ts,tsx,md,yml,json}"'
